version: "3.3"
# see https://github.com/portainer/portainer-compose/blob/master/traefik/docker-compose.yml
services:
  traefik:
    container_name: traefik
    image: traefik:v2.9
    restart: unless-stopped
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --api.dashboard=true
      - --providers.docker
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=gateway
      - --log.level=ERROR
      - --certificatesresolvers.leresolver.acme.httpchallenge=true
      #Set your email address here, is for the generation of SSL certificates with Let's Encrypt.       - --certificatesresolvers.leresolver.acme.email=${EMAIL} 
      - --certificatesresolvers.leresolver.acme.storage=./acme.json
      - --certificatesresolvers.leresolver.acme.httpchallenge.entrypoint=web
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./users_credentials:/users_credentials:ro"
      - "./acme.json:/acme.json"
    labels:
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

      # DASHBOARD
      - "traefik.enable=true"

      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN:-localhost}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=leresolver"
      - "traefik.http.routers.traefik.middlewares=traefik-auth"
      # https://doc.traefik.io/traefik/middlewares/http/digestauth/
      # htdigest users_credentials traefik admin
      - "traefik.http.middlewares.traefik-auth.digestauth.usersfile=/users_credentials"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    networks:
      - gateway

  portainer:
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      # Frontend
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`portainer.${DOMAIN:-localhost}`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.services.frontend.loadbalancer.server.port=9000"
      - "traefik.http.routers.frontend.service=frontend"
      - "traefik.http.routers.frontend.tls.certresolver=leresolver"

      # Edge
      - "traefik.http.routers.edge.rule=Host(`edge.${DOMAIN:-localhost}`)"
      - "traefik.http.routers.edge.entrypoints=websecure"
      - "traefik.http.services.edge.loadbalancer.server.port=8000"
      - "traefik.http.routers.edge.service=edge"
      - "traefik.http.routers.edge.tls.certresolver=leresolver"
    networks:
      - gateway

volumes:
  portainer_data:
    name: portainer_data

networks:
  gateway:
    name: gateway

