version: '3'

services:
  traefik:
    container_name: traefik
    image: "traefik:latest"
    restart: unless-stopped
    command:
      - --entrypoints.web.address=:80
      - --api.dashboard=true
      - --providers.docker
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=gateway
      - --log.level=ERROR
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"

      # DASHBOARD
      - "traefik.enable=true"

      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN:-localhost}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    networks:
      - gateway

networks:
  gateway:
    name: gateway
    