version: '3.9'

services:
  mysql80:
    container_name: mysql80
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
    networks:
      - mysql80
      - gateway
    volumes:
      - ${VOLUMES_PATH:-./volumes}/mysql:/var/lib/mysql:delegated
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.mysql80.rule=Host(`mysql80.${DOMAIN:-localhost}`)"

networks:
  mysql80:
    name: mysql80 
  gateway:
    external: true
