version: "3.8"

services:
  httpd:
    build:
      context: ./httpd
    ports:
      - '${HTTPD_PORT:-81}:80'
    volumes:
      - ./httpd/sites:/usr/local/apache2/conf/sites:ro
      - ${APP_CODE_PATH:-.}:/var/www:ro
      - ${LOG_PATH:-./log}/httpd:/usr/local/apache2/logs:delegated
