version: '3'
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.9.3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data 
    ports:
      # - "8000:8000"
      - "9443:9443"

volumes:
  portainer_data:
    name: portainer_data

