version: "3.8"

services:
  mysql:
    platform: linux/x86_64 # added for apple M1
    build:
      context: ./mysql
      args:
        - MYSQL_GENERAL_LOG=${MYSQL_GENERAL_LOG:-false}
        - MYSQL_VERSION=${MYSQL_VERSION:-latest}
    ports:
      - '${MYSQL_PORT:-3306}:3306'
    environment:
      - MYSQL_VERSION=${MYSQL_VERSION:-latest}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-secret}
    volumes:
      - mysql:/var/lib/mysql
      - ${LOG_PATH:-./log}/mysql:/var/log/mysql:delegated

volumes:
  mysql:
