version: "3.8"

services:
  mongo:
    build: 
      context: ./mongo
      args: 
        - MONGO_VERSION=${MONGO_VERSION:-latest}
    ports:
      - '${MONGO_PORT:-27017}:27017'
    volumes:
      - ${VOLUMES_PATH:-./volumes}/mongo:/data/db:delegated
      - ${VOLUMES_PATH:-./volumes}/mongo_config:/data/configdb:delegated
